import { TutorialGachaScreen } from '../../src/features/tutorial/TutorialGachaScreen';
import { useTutorialStore } from '../../src/stores/tutorialStore';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import '../../src/index.css';
import '../../src/styles/game-design.css';
import { BottomNav } from '../../src/components/layout/BottomNav';
import { usePlayerStore } from '../../src/stores/playerStore';
import { useUnitStore } from '../../src/stores/unitStore';
import { usePartyStore } from '../../src/stores/partyStore';
import { useAuthStore } from '../../src/stores/authStore';
import { useLoginBonusStore } from '../../src/stores/loginBonusStore';
import { UNIT_MASTER } from '../../src/data/units';
import { MissionsPage } from '../../src/features/missions/MissionsPage';
import { QuestsPage } from '../../src/features/quests/QuestsPage';
import { ShopPage } from '../../src/features/shop/ShopPage';
import { CollectionPage } from '../../src/features/collection/CollectionPage';
import { GuildPage } from '../../src/features/guild/GuildPage';
import { SummonPage } from '../../src/features/summon/SummonPage';
import { UnitDetailPage } from '../../src/features/units/UnitDetailPage';
import { UnitsPage } from '../../src/features/units/UnitsPage';
import { ProfilePage } from '../../src/features/profile/ProfilePage';
import { LoginPage } from '../../src/features/auth/LoginPage';
import { RegisterPage } from '../../src/features/auth/RegisterPage';
import { ItemsPage } from '../../src/features/items/ItemsPage';
import { GiftBoxPage } from '../../src/features/gifts/GiftBoxPage';
import { EnhancePage } from '../../src/features/enhance/EnhancePage';
import { PartyPage } from '../../src/features/party/PartyPage';
import { FriendSelectPage } from '../../src/features/friends/FriendSelectPage';
import { PvPPage } from '../../src/features/pvp/PvPPage';
import { EquipmentPage } from '../../src/features/equipment/EquipmentPage';
import { HomePage } from '../../src/features/home/HomePage';
import { FriendPage } from '../../src/features/social/FriendPage';
import { RaidPage } from '../../src/features/raid/RaidPage';
import { BattlePage } from '../../src/features/battle/BattlePage';
usePlayerStore.setState(s=>({player:{...s.player,name:'アストラ',diamond:12480,gold:248650,rank:24,stamina:42,maxStamina:80,staminaRecoveryTime:Date.now()+180000},items:[{itemId:'item_exp_s',quantity:10},{itemId:'item_summon_ticket_ssr',quantity:1}]}));
useUnitStore.setState({ownedUnits:[],awakeningCrystals:{}});
useTutorialStore.setState({initialGachaDone:false,completed:false});
const sample=UNIT_MASTER.filter((_,i)=>i<16 || (i>60 && i<65));
sample.forEach(m=>useUnitStore.getState().addUnit(m.id));
usePartyStore.setState({parties:[{id:'party_default',name:'パーティ1',slots:useUnitStore.getState().ownedUnits.slice(0,5).map(u=>u.instanceId),leaderId:useUnitStore.getState().ownedUnits[0].instanceId}]});
useAuthStore.setState({syncSummonResult:async()=>{}});
useLoginBonusStore.setState({canClaim:()=>false,markLoggedInToday:()=>false});
(window as any).__stores={player:usePlayerStore,units:useUnitStore,party:usePartyStore,tutorial:useTutorialStore};
const params=new URLSearchParams(location.search);
const page=params.get('page') || 'HomePage';
const pages={TutorialGachaScreen,MissionsPage,QuestsPage,ShopPage,CollectionPage,GuildPage,SummonPage,UnitDetailPage,UnitsPage,ProfilePage,LoginPage,RegisterPage,ItemsPage,GiftBoxPage,EnhancePage,PartyPage,FriendSelectPage,PvPPage,EquipmentPage,HomePage,FriendPage,RaidPage,BattlePage};
const Page=pages[page as keyof typeof pages] || HomePage;
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><div className="app-shell has-navigation"><Routes><Route path="/units/:instanceId" element={<UnitDetailPage/>}/><Route path="*" element={<Page/>}/></Routes><BottomNav/></div></BrowserRouter></StrictMode>);
